### ISSUE TITLE
Create Epic Definition of Done

### ISSUE THREAD

**Issue by micharubin-pdm** [FearlessSolutions/ICTS#30]
Completion of an epic must meet the following criteria:

- [ ] All In Scope Items completed
- [ ] 508 Compliance 
- [ ] Mobile Responsive
- [ ] Usage Analytics Logging
- [ ] Security Compliant
- [ ] Multi-Browser Support - What browsers and versions do we need for internal users?
- [ ] Automatic/Smoke/Regression Testing - front end is covered, need a plan for API (may need to accept as technical debt, likely postman)
- [ ] Release Planning
- [ ] PO Approves of Epic at Demo
- [ ] Project Manager approves of Epic at Demo
- [ ] Plain Language Used
- [ ] Content Supplied by PO
- [ ] Change Request Form filled out and approved (Prod)
